name: Flyway CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flyway-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Flyway
        run: |
          wget -q https://download.red-gate.com/maven/release/com/redgate/flyway-commandline/11.20.3/flyway-commandline-11.20.3-linux-x64.tar.gz
          tar -xzf flyway-commandline-11.20.3-linux-x64.tar.gz

      - name: Flyway Validate
        env:
          FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          ./flyway-11.20.3/flyway -url="$FLYWAY_URL" -user="$FLYWAY_USER" -password="$FLYWAY_PASSWORD" validate

      - name: Flyway Migrate
        env:
          FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          ./flyway-11.20.3/flyway -url="$FLYWAY_URL" -user="$FLYWAY_USER" -password="$FLYWAY_PASSWORD" migrate
